import type { NextPage } from "next";
import { useState, useEffect } from "react";
import Head from "next/head";
import Img from "next/image";

//components
import { BookingForm } from "../components/bookingForm";

//styles
import { Container, BackgroundColor } from "./styles";
import { BookingDashboard } from "../components/bookingDashboard";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <BackgroundColor></BackgroundColor>
      <div className='booking'>
        <BookingForm />
      </div>
      {/* <BookingDashboard /> */}
    </Container>
  );
};

export default Home;
