import React from 'react'
import type { NextPage } from "next";
import Head from "next/head";

//components
import { BookingForm } from "../components/bookingForm";

//styles
import { Container, BackgroundColor } from "./styles";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <BackgroundColor></BackgroundColor>
      <div className='booking'>
        <BookingForm />
      </div>
    </Container>
  );
};

export default Home;
