import type { NextPage } from 'next'
import { useState, useEffect } from 'react'
import Head from 'next/head'

//components
import { BookingButton } from '../components/bookingButton'

//styles
import { Container } from './styles'

//services
import { api } from '../services/api'
import { BookingDashboard } from '../components/bookingDashboard'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <BookingButton />
      <BookingDashboard />
    </Container>
  )
}

export default Home
